version: '3'
services:
  backend:
    image: vedantchimote/studentsystembackend:latest
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  frontend:
    image: vedantchimote/studentsystemfrontend:latest
    ports:
      - "3000:3000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fullstack
    volumes:
      - mysql-data:/var/lib/mysql
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

volumes:
  mysql-data: